// Console output simulation...

uses 'console';
uses '../statistic.feh';
uses 'reports.feh';

function toConsole( array data ) {
	number tableLength = 0;
	number column1Length = 0;

	data.each() using ( row ) {
		number keyLength = row['key'].length();
		if( keyLength > column1Length )
			column1Length = keyLength;
	};
	
	tableLength = 2 + column1Length + 3 + 5 + 2;
	
	data.each() using ( row ) {
		string key = row['key'];
		string value = "" + row['value'];
		
		for( number i = 0; i < tableLength; i++ )
			Console.print( "-" );
		
		Console.print( "\n| ${key}" );
		
		if( key.length() < column1Length ) {
			number extraSpaces = 0;
			while( ( key.length() + extraSpaces ) < column1Length ) {
				Console.print( " " );
				extraSpaces++;
			}
		}
		
		Console.print( " | ${value}" );
		
		if( value.length() < 5 ) {
			number extraSpaces = 0;
			while( ( value.length() + extraSpaces ) < 5 ) {
				Console.print( " " );
				extraSpaces++;
			}
		}
			
		Console.print( " |\n" );
	};

	for( number i = 0; i < tableLength; i++ )
		Console.print( "-" );

	Console.print( "\n" ); 
}

object incoming;
object processTime;
object closureStatus;

incoming = new Reports.IncomingErrands();
incoming.addTimeframe( new Statistic.Timeframe( "2008-01-01", "2008-01-15" ) );
incoming.setTimeGroupFormat( new Statistic.WeekdayFormat() );

processTime = new Reports.ErrandProcessTime();
processTime.addTimeframe( new Statistic.Timeframe( "2008-01-01", "2008-01-15" ) );
processTime.setTimeGroupFormat( new Statistic.MinuteFormat() );

closureStatus = new Reports.ErrandClosureStatus();

Console.print( "\n" );

Console.println( "Incoming" );
toConsole( incoming.getData() );

Console.print( "\n" );

Console.println( "Process time" );
toConsole( processTime.getData() );

Console.print( "\n" );

Console.println( "Closure status" );
toConsole( closureStatus.getData() );

Console.print( "\n" );

